=begin
  Thif rake file is use to configure the gem.
  This file is generated by jeweler. 
=end
# encoding: utf-8

require 'rubygems'
require 'bundler'
begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end
require 'rake'

require 'jeweler'
lib = File.expand_path('../lib/', __FILE__)  
$:.unshift lib unless $:.include?(lib) 
Jeweler::Tasks.new do |gem|
  # gem is a Gem::Specification... see http://docs.rubygems.org/read/chapter/20 for more options
  gem.name = "act_as_buddy"
  gem.homepage = "http://github.com/kannancet/act_as_buddy"
  gem.license = "BSD"
  gem.summary = "A gem to implement self relation on any table."
  gem.description = "Act-as-Buddy is a gem to allow any model to implement self relation. For eg: the friendships of a user can be implemented easily by self relation technique of act_as_buddy. Any Model can be buddied or lopped on to itself. Main uses would be for Users create friends etc.. Eg: User has many friends and friends are members of users table itself. This is expected to be heavily useful in social networking domain."
  gem.email = "krxcet@gmail.com"
  gem.authors = ["kannancet"]
  gem.files = Dir.glob("{bin,lib}/**/*")
  gem.test_files = Dir.glob("{spec,test}/**/*.rb")
  # dependencies defined in Gemfile
end
Jeweler::RubygemsDotOrgTasks.new

# require 'rspec/core/rake_task'
# RSpec::Core::RakeTask.new('spec')

require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'lib' << 'test'
  test.pattern = 'test/**/test_*.rb'
  test.verbose = true
end

require 'rcov/rcovtask'
Rcov::RcovTask.new do |test|
  test.libs << 'test'
  test.pattern = 'test/**/test_*.rb'
  test.verbose = true
  test.rcov_opts << '--exclude "gems/*"'
end

 task :default => :test

require 'rdoc/task'
Rake::RDocTask.new do |rdoc|
  version = File.exist?('VERSION') ? File.read('VERSION') : ""

  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "act_as_buddy #{version}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end
